test all pass, after much toil I only needed sleeps in one of them

diff --git a/tests/test-funcs b/tests/test-funcs
--- a/tests/test-funcs
+++ b/tests/test-funcs
@@ -1,39 +1,9 @@
 # -*- sh -*-
-ALLOW_DIR="$HOME/.local/share/direnv/allow/"
-
-_count_allowed () {
-    count=$(ls -1Uqa "$ALLOW_DIR" | grep -c '.*')
-    echo "in count_allowed $count"
-}
-
-wait_direnv () {
-    original_count=$1
-    local count=0
-    _count_allowed
-    echo "in wait_on_allowed, original count: $original_count"
-    echo "in wait_on_allowed $count"
-    while [ $count -eq $original_count ]; do
-        sleep 0.1
-        _count_allowed
-        echo "in wait_on_allowed $count"
-    done
-    echo "done waiting: $count"
-}
-
-begin_direnv () {
-    count=0
-    _count_allowed
-}
-
-end () {
-    begin_direnv
-    direnv deny .
-    wait_direnv $count
-}
-
 end_test () {
-    direnv deny .
+    # try hard to cleanup the .envrc's we allowed during testing:
+    direnv deny . > /dev/null 2>&1 || true
     rm -f .envrc
+    direnv prune
     case $2 in
         "pass")
             echo "$1 pass"
@@ -44,7 +14,7 @@ end_test () {
             exit 1
             ;;
         *)
-            echo "end_test error: please call with pass or fail"
+            echo "$1 end_test error: please call with pass or fail"
             exit 2
     esac
 }
